micronaut:
    application:
        name: micronaut-opa-demo
    server:
        port: 8080
    heartbeat:
        enabled: false
    endpoints:
        health:
            enabled: true
            sensitive: false
